### ISSUE TITLE
Other KMC Codes

### ISSUE THREAD

**Issue by holyone2** [mhoffman/kmos#17]
Hiya, thought I might point out this KMC Code:

 Zacros: http://zacros.org/ (http://www.homepages.ucl.ac.uk/~ucecmst/software.html)

I'm currently looking for KMC code that can deal with long range lateral interactions efficiently, please keep me posted if anyone is aware of such a code.

**Comment by mhoffman** [comment]
Thanks, I made note of it. When you say long range interaction: could you be a bit more specific? How many sites influence the rate constant? How many different species per site?

**Comment by holyone2** [comment]
Hi, sorry yes. By long range I mean a pair-wise additive interaction potential which requires interaction up to approximately the 10th nearest neighbour. Each site binary (1 or 0) spin i.e. two species.

**Comment by mhoffman** [comment]
That sounds 3-4 times more long range than what surface chemistry is usually aiming for :-). I cannot think of a ready-to-use kMC code for this on the top of my head. With that many processes you will have to evaluate rate constants on the fly. Doing this efficiently typically involves some trickery (i.e. symbolic math) which depending on the specific form of your interaction.

**Comment by holyone2** [comment]
I see, but I could imagine it would be possible to create a lookup table of precalculated additive terms for the net contribution from each nearest neighbour 'shell'. And then on the fly add on the appropriate amount based on the current configuration.

Zacros caught my eye as it appears to be able to handle 8th nearest neighbour interactions according to the docs (http://zacros.org/index.php/tutorials/9-tutorial-3-cluster-expansion-for-oxygen-on-pt-111?showall=&start=1). I'm interested in doing simulating the long range charge-charge interactions involved in simulating proton binding to surfaces (http://dx.doi.org/10.1021/la9621325).

**Comment by mhoffman** [comment]
I would claim the *number* of sites (occupancies) contributing to any one reaction constant is actually a better measure than sheer distance for both size of the problem both in terms of what the kMC code has to conquer and what the complexity of the physics underlying the model is. 

A long range charge-charge (i.e. classical monopoles?) interaction certainly sounds like a pretty challenging scenario here. Can you rule out certain to distances (i.e. very small ones) at least for the temperature window you are looking at? And maybe can you make upper and lower bounds for the expected charge concentration? Maybe that could help to reduce the number of processes that actually have to be considered.

The best kmos can do right know in terms lateral interaction is the lat_int backend (compile with "kmos export -blat_int <filename>"). But I would be glad to learn more about it if zacros performs better for that many different lateral interactions.

**Comment by holyone2** [comment]
I see what your saying, indeed thermal limits impose the maximum distance
that is viable, and full coverage is unlikely which lowers the upper bound
of the charge concentration (and therefore number of sites contributing).

Is there any documentation for the lat_int backend? What does it do?

Thanks!
