### ISSUE TITLE
TOF not shown

### ISSUE THREAD

**Issue by xunhuazhao** [mhoffman/kmos#23]
Hi, I found another problem:
I run kmos with "kmos view" in an API way, everything looks fine except that TOF plot is just blank :(
I do see nice TOF plot in Fig. 1.5 in the kmos documentation (release 0.3.13).

Could you check this issue? I am using Ubuntu 14.04.

Thanks.

**Comment by jmlorenzi** [comment]
Hi xunhunzhao,

I have had this problem too in the past, but not for every model. Could you please comment a bit on the kind of model you are trying out? (maybe share the xml file)
In my case I suspect that the missing TOF plots has to do with the fact that I have two TOFs in my model which differ by some orders of magnitude in value. Is that you case?

**Comment by xunhuazhao** [comment]
Thanks for your comments, jmlorenzi.

My model is simply something close to "AB_model.py" in the example package. I tested the original AB_model.py and found the same problem. So it seems the magnitude is not the problem. 

Anyways, thanks a lot for your information.

**Comment by jmlorenzi** [comment]
I suspect the problem might actually be in the example

please, try changing

pt.add_process(name='AB_react_%s' % name,rate_constant='1/(beta*h)*exp(-beta*E_react*eV)',
condition_list=[Condition(coord=coord, species='A'),Condition(coord=neighbor, species='B')],action_list=[Action(coord=coord, species='empty'),Action(coord=neighbor, species='empty')],)

to

pt.add_process(name='AB_react_%s' % name,rate_constant='1/(beta*h)*exp(-beta*E_react*eV)',
condition_list=[Condition(coord=coord, species='A'),Condition(coord=neighbor, species='B')],action_list=[Action(coord=coord, species='empty'),Action(coord=neighbor, species='empty')],
tof_count={'TOF':1},)

in the script (i.e., add the 'tof_count' keyword to each process definition). Then regenerate the xml file, recompile the model, and try again.
And please let us now if this works.

**Comment by xunhuazhao** [comment]
It works. Thank you very much for help.

**Comment by mhoffman** [comment]
I am glad you found a solution! So, basically you have to 'setup' the TOF's via tof_count before anything gets counted. kmos tries to be nimble here and only counts the rates you explicitly ask for. Using dictionary also gives you all the freedom to (a) count one process towards several rates and (b) count several processes towards the same rate.
