### ISSUE TITLE
"species color" seems not working

### ISSUE THREAD

**Issue by xunhuazhao** [mhoffman/kmos#26]
All colors seems determined by the atom names, no matter if "species color" is set.
Could you pls have a look? Thx.

**Comment by mhoffman** [comment]
The purpose of the species color changes only the look in the editor GUI 'kmos edit ...' but not on screen for 'kmos view'. [1] If you wanted to change the look on screen you would have to modify e.g. kmos/run.py:get_atoms() and hack how kmos uses ASE using jmol colors ...


[1] https://kmos.readthedocs.org/en/latest/reference/index.html#kmos.types.Species
