### ISSUE TITLE
2D lattice generation

### ISSUE THREAD

**Issue by diosak** [mhoffman/kmos#28]
Hello,

I am trying to generate a simple 2D (lets say 10 by 5) lattice to use with my own equations for the simulation of conductive paths' generation. 
Could someone help me out as I know almost nothing about python?

Thank you in advance!
Dionisis

**Comment by mhoffman** [comment]
From your description alone it is very hard to tell, whether lattice kMC is even the right approach for your problem. For basic lattice kMC applications with kmos you shouldn't need to know any python. However you would have to work through the intro tutorial[1], to see what a lattice kMC model involves. If you have generated and export a model using your installation you will find the file called kmc_settings.py in the corresponding output directory. In there is a variable on the 2nd line, like

    simulation_size = 20

which you could set to e.g.

    simulation_size = (10, 5)

However you first have to work out whether your equation can be expressed in terms of elementary steps and rate constants.


[1] https://kmos.readthedocs.org/en/latest/tutorials/index.html#a-first-kmc-model-the-api-way
