### ISSUE TITLE
my first kMC model-name.offset.lattice

### ISSUE THREAD

**Issue by jiangwangzhagn** [mhoffman/kmos#44]
I try the first model following the guide. however, after the step of name.offset.lattice,ipython showed an error:
NameError                                 Traceback (most recent call last)
<ipython-input-18-fac787b39f1c> in <module>()
----> 1 name.offset.lattice

NameError: name 'name' is not defined

**Comment by jiangwangzhagn** [comment]
and the whole code as following:
`In [1]: from kmos.types import *

In [2]: from kmos.io import *

In [3]: import numpy as np

In [4]: pt = Project()

In [5]: pt.set_meta(author = 'Your Name',
   ...:             email = 'your.name@server.com',
   ...:             model_name = 'MyFirstModel',
   ...:             model_dimension = 2,)

In [6]: pt.add_species(name='empty')
Out[6]: [SPECIES] Name: empty Color: no color set.

In [7]: pt.add_species(name='CO',
   ...:                representation="Atoms('CO',[[0,0,0],[0,0,1.2]])")
Out[7]: [SPECIES] Name: CO Color: no color set.

In [8]: layer = pt.add_layer(name='simple_cubic')

In [9]: layer.sites.append(Site(name='hollow', pos='0.5 0.5 0.5',
   ...:                         default_species='empty'))

In [10]: pt.lattice.cell = np.diag([3.5, 3.5, 10])

In [11]: pt.add_parameter(name='T', value=600., adjustable=True, min=400) max=80 
Out[11]: [PARAMETER] Name: T Value: 600.0

In [12]: pt.add_parameter(name='p_CO', value=1., adjustable=True, min=1=1.e2)max 
Out[12]: [PARAMETER] Name: p_CO Value: 1.0

In [13]: pt.add_parameter(name='A', value='(3.5*angstrom)**2')
Out[13]: [PARAMETER] Name: A Value: (3.5*angstrom)**2

In [14]: pt.add_parameter(name='deltaG', value='-0.5', adjustable=True,
   ....:                            min=-1.3, max=0.3)
Out[14]: [PARAMETER] Name: deltaG Value: -0.5

In [15]: coord = pt.lattice.generate_coord('hollow.(0,0,0).simple_cubic')

In [16]: pt.add_process(name='CO_adsorption',
   ....:                conditions=[Condition(coord=coord, species='empty')],
   ....:                actions=[Action(coord=coord, species='CO')],
   ....:                rate_constant='p_CO*bar*A/sqrt(2*pi*umass*m_CO/beta)')
Out[16]: 
[PROCESS] Name:CO_adsorption
     Rate: p_CO*bar*A/sqrt(2*pi*umass*m_CO/beta)
Conditions: [[COND_ACT] Species: empty Coord:[COORD] hollow.(0, 0, 0).simple_cubic
]
Actions: [[COND_ACT] Species: CO Coord:[COORD] hollow.(0, 0, 0).simple_cubic
]

In [17]: pt.add_process(name='CO_desorption',
   ....:                conditions=[Condition(coord=coord, species='CO')],
   ....:                actions=[Action(coord=coord, species='empty')],
   ....:                rate_constant='p_CO*bar*A/sqrt(2*pi*umass*m_CO/(beta*deltaG*eV)')
Out[17]: 
[PROCESS] Name:CO_desorption
     Rate: p_CO*bar*A/sqrt(2*pi*umass*m_CO/beta)*exp(beta*deltaG*eV)
Conditions: [[COND_ACT] Species: CO Coord:[COORD] hollow.(0, 0, 0).simple_cubic
]
Actions: [[COND_ACT] Species: empty Coord:[COORD] hollow.(0, 0, 0).simple_cubic
]

In [18]: 

In [18]: name.offset.lattice
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-18-fac787b39f1c> in <module>()
----> 1 name.offset.lattice

NameError: name 'name' is not defined
`

**Comment by jiangwangzhagn** [comment]
and I tried skip the step"name.offset.lattice",going on. when running the code : "import kmos.cli
kmos.cli.main('export myfirst_kmc.xml')"in ipython, there is an exception`In [22]: kmos.cli.main('export myfirst_kmc.xml')
No export path provided. Exporting to myfirst_kmc_local_smart
/usr/local/lib/python2.7/dist-packages/kmos
Unknown vendor: "gfortran"
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "f2py_selected_kind" sources
f2py options: []
f2py:> /tmp/tmpwKHof4/src.linux-x86_64-2.7/f2py_selected_kindmodule.c
creating /tmp/tmpwKHof4/src.linux-x86_64-2.7
Reading fortran codes...
	Reading file 'f2py_selected_kind.f90' (format:free)
Post-processing...
	Block: f2py_selected_kind
			Block: kind
				Block: real_kind
				Block: int_kind
Post-processing (stage 2)...
	Block: f2py_selected_kind
		Block: unknown_interface
			Block: kind
				Block: real_kind
				Block: int_kind
Building modules...
	Building module "f2py_selected_kind"...
		Constructing F90 module support for "kind"...
			Constructing wrapper function "kind.real_kind"...
			  kind_value = real_kind([p,r])
			Constructing wrapper function "kind.int_kind"...
			  kind_value = int_kind([p,r])
	Wrote C/API module "f2py_selected_kind" to file "/tmp/tmpwKHof4/src.linux-x86_64-2.7/f2py_selected_kindmodule.c"
	Fortran 90 wrappers are saved to "/tmp/tmpwKHof4/src.linux-x86_64-2.7/f2py_selected_kind-f2pywrappers2.f90"
  adding '/tmp/tmpwKHof4/src.linux-x86_64-2.7/fortranobject.c' to sources.
  adding '/tmp/tmpwKHof4/src.linux-x86_64-2.7' to include_dirs.
copying /usr/lib/python2.7/dist-packages/numpy/f2py/src/fortranobject.c -> /tmp/tmpwKHof4/src.linux-x86_64-2.7
copying /usr/lib/python2.7/dist-packages/numpy/f2py/src/fortranobject.h -> /tmp/tmpwKHof4/src.linux-x86_64-2.7
  adding '/tmp/tmpwKHof4/src.linux-x86_64-2.7/f2py_selected_kind-f2pywrappers2.f90' to sources.
build_src: building npy-pkg config files
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
customize Gnu95FCompiler
Could not locate executable gfortran
Could not locate executable f95
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/numpy/f2py/f2py2e.py", line 594, in main
    run_compile()
  File "/usr/lib/python2.7/dist-packages/numpy/f2py/f2py2e.py", line 580, in run_compile
    setup(ext_modules = [ext])
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/command/build.py", line 39, in run
    old_build.run(self)
  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/command/build_ext.py", line 199, in run
    fcompiler.customize(self.distribution)
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/fcompiler/__init__.py", line 464, in customize
    self.find_executables()
  File "/usr/lib/python2.7/dist-packages/numpy/distutils/fcompiler/__init__.py", line 354, in find_executables
    raise CompilerNotFound('%s: f90 nor f77' % ctype)
numpy.distutils.fcompiler.CompilerNotFound: gnu95: f90 nor f77
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-22-710325f628bf> in <module>()
----> 1 kmos.cli.main('export myfirst_kmc.xml')

/usr/local/lib/python2.7/dist-packages/kmos/cli.pyc in main(args)
    314            and not options.source_only:
    315             os.chdir(export_dir)
--> 316             build(options)
    317             for out in glob('kmc_*'):
    318                 if os.path.exists('../%s' % out):

/usr/local/lib/python2.7/dist-packages/kmos/utils/__init__.pyc in build(options)
    393 
    394     if not isfile('kind_values_f2py.f90'):
--> 395         evaluate_kind_values('kind_values.f90', 'kind_values_f2py.f90')
    396 
    397     for src_file in src_files:

/usr/local/lib/python2.7/dist-packages/kmos/utils/__init__.pyc in evaluate_kind_values(infile, outfile)
    338             line = '%s%s%s\n' % (
    339                     match['before'],
--> 340                     real_kind(match['args']),
    341                     match['after'],)
    342         outfile.write(line)

/usr/local/lib/python2.7/dist-packages/kmos/utils/__init__.pyc in real_kind(args)
    314         """
    315         args, kwargs = parse_args(args)
--> 316         return import_selected_kind().real_kind(*args, **kwargs)
    317 
    318     infile = file(infile)

/usr/local/lib/python2.7/dist-packages/kmos/utils/__init__.pyc in import_selected_kind()
    280                 raise Exception('Could create selected_kind module\n'
    281                 + '%s\n' % os.path.abspath(os.curdir)
--> 282                 + '%s\n' % os.listdir('.'))
    283         return f2py_selected_kind.kind
    284 

Exception: Could create selected_kind module
/home/jiangzhen/myfirst_kmc_local_smart/src
['lattice.f90', 'kmc_settings.py', 'assert.ppc', 'kind_values.f90', 'proclist.f90', 'base.f90', 'main.f90', 'f2py_selected_kind.f90', 'kind_values_f2py.f90']
`

**Comment by mhoffman** [comment]
Hi jiangwangzhagn

thank you for your interest in kmos. The  `name.offset.lattice` line you mention above is not meant for immediate evaluation by Python. Instead it shows the general scheme (as a string) how complex coordinates can be described. If you write `hollow` it will be internally expanded to `hollow.(0,0,0).default` if `default` is your only layer. If you want to describe `hollow` in the unit cell above you will write a condition like `CO@hollow.(0,1,0)`. I fixed the tutorial to state "\<site-name\>.\<offset\>.\<lattice\>" now to avoid confusion.

The second issue you mention most likely means that you have no Fortran compiler installed or that f2py cannot find the compiler. Steps for debugging could be

1. Enter `gfortran -v` on the console
1. Enter `ifort -v`
1. Enter `f2py -c --help-fcompiler`
1. Enter either `export F2PY_FCOMPILER=gfortran` or `export F2PY_FCOMPILER=intelem` depending on your results above  and run the `kmos export` step again but make sure that you delete the export directory `..._local_smart` before.

Best of luck.

**Comment by jiangwangzhagn** [comment]
mhoffman， thanks  a lot.
u are so NB ! follow ur suggestion, I run the first model successfully!
thanks again.
