### ISSUE TITLE
run the example of "AB_model.py"

### ISSUE THREAD

**Issue by jiangwangzhang** [mhoffman/kmos#48]
**hi good morning.
sorry, I met a problem,when I run the example of "AB_model.py":**
`In [1]: from kmos.types import *

In [2]: from kmos.io import *

In [3]: import numpy as np

In [4]: pt = Project()

In [5]: pt.set_meta(author = 'JZ',
   ...:             email = 'jz@jz.com',
   ...:             model_name = 'JZ',
   ...:             model_dimension = 2,)

In [6]: pt.add_species(name='empty')
Out[6]: [SPECIES] Name: empty Color: no color set.

In [7]: pt.add_species(name='A', representation="Atoms('O')")
Out[7]: [SPECIES] Name: A Color: no color set.

In [8]: pt.add_species(name='B', representation="Atom\
   ...: s('CO', [[0,0,0],[0,0,1.2]])")
Out[8]: [SPECIES] Name: B Color: no color set.

In [9]: layer = Layer(name='default')

In [10]: layer.sites.append(Site(name='a'))

In [11]: pt.add_layer(layer)
Out[11]: 
[LAYER] default
[
[[SITE] a            (default_species) [ 0.  0.  0.] ]
]

In [12]: pt.species_list.default_species = 'empty'

In [13]: parameters = {}

In [14]: parameters['p_COgas'] = {'value':1., 'adjustable':True,
   ....:                                          'min':1.e-13, 'max':1.e2,
   ....:                                          'scale':'log'}

In [15]: parameters['p_O2gas'] = {'value':1., 'adjustable':True,
   ....:                                          'min':1.e-13, 'max':1.e2,
   ....:                                          'scale':'log'}

In [16]: parameters['T'] = {'value':600}

In [17]: parameters['A'] = {'value':1.552e-19}

In [18]: parameters['E_bind_O2'] = {'value':-2.138}

In [19]: parameters['E_bind_CO'] = {'value':-1.9}

In [20]: parameters['E_react'] = {'value': 0.9}

In [21]: for key, value in parameters.iteritems():
   ....:     pt.add_parameter(name=key, **value)
   ....:     

In [22]: coord = pt.lattice.generate_coord('a.(0,0,0).default')

In [23]: up = pt.lattice.generate_coord('a.(0,1,0).default')

In [24]: right = pt.lattice.generate_coord('a.(1,0,0).default')

In [25]: down = pt.lattice.generate_coord('a.(0,-1,0).default')

In [26]: left = pt.lattice.generate_coord('a.(-1,0,0).default')

In [27]: pt.add_process(name='A_adsorption',
   ....:                    rate_constant='p_O2gas_bar_A/sqrt(2_pi_m_O2_umass/beta)',
   ....:                    condition_list=[Condition(coord=coord, species='empty')],
   ....:                    action_list=[Action(coord=coord, species='A')],)
Out[27]: 
[PROCESS] Name:A_adsorption
     Rate: p_O2gas_bar_A/sqrt(2_pi_m_O2_umass/beta)
Conditions: [[COND_ACT] Species: empty Coord:[COORD] a.(0, 0, 0).default
]
Actions: [[COND_ACT] Species: A Coord:[COORD] a.(0, 0, 0).default
]

In [28]: pt.add_process(name='A_desorption',
   ....:                    rate_constant='p_O2gas_bar_A/sqrt(2_pi_m_O2_umass/beta)_exp(beta_(E_bind_O2-mu_O2gas)_eV)',
   ....:                    condition_list=[Condition(coord=coord, species='A')],
   ....:                    action_list=[Action(coord=coord, species='empty')],)Out[28]: 
[PROCESS] Name:A_desorption
     Rate: p_O2gas_bar_A/sqrt(2_pi_m_O2_umass/beta)_exp(beta_(E_bind_O2-mu_O2gas)_eV)
Conditions: [[COND_ACT] Species: A Coord:[COORD] a.(0, 0, 0).default
]
Actions: [[COND_ACT] Species: empty Coord:[COORD] a.(0, 0, 0).default
]

In [29]: pt.add_process(name='B_adsorption',
   ....:                    rate_constant='p_COgas_bar_A/sqrt(2_pi_m_CO_umass/beta)',
   ....:                    condition_list=[Condition(coord=coord, species='empty')],
   ....:                    action_list=[Action(coord=coord, species='B')],)
Out[29]: 
[PROCESS] Name:B_adsorption
     Rate: p_COgas_bar_A/sqrt(2_pi_m_CO_umass/beta)
Conditions: [[COND_ACT] Species: empty Coord:[COORD] a.(0, 0, 0).default
]
Actions: [[COND_ACT] Species: B Coord:[COORD] a.(0, 0, 0).default
]

In [30]: pt.add_process(name='B_desorption',
   ....:                    rate_constant='p_COgas_bar_A/sqrt(2_pi_m_CO_umass/beta)_exp(beta_(E_bind_CO-mu_COgas)_eV)',
   ....:                    condition_list=[Condition(coord=coord, species='B')],
   ....:                    action_list=[Condition(coord=coord, species='empty')],)
Out[30]: 
[PROCESS] Name:B_desorption
     Rate: p_COgas_bar_A/sqrt(2_pi_m_CO_umass/beta)_exp(beta_(E_bind_CO-mu_COgas)_eV)
Conditions: [[COND_ACT] Species: B Coord:[COORD] a.(0, 0, 0).default
]
Actions: [[COND_ACT] Species: empty Coord:[COORD] a.(0, 0, 0).default
]

In [31]: for neighbor, name in [(right, 'right'),
   ....:                            (left, 'left'),
   ....:                            (up, 'up'),
   ....:                            (down, 'down')]:
   ....:     pt.add_process(name='AB_react_%s' % name,
   ....:                            rate_constant='1/(beta_h)_exp(-beta_E_react_eV)',
   ....:                            condition_list=[Condition(coord=coord, species='A'),
   ....:                                            Condition(coord=neighbor, species='B')],
   ....:                            action_list=[Action(coord=coord, species='empty'),
   ....:                                        Action(coord=neighbor, species='empty')],
   ....:                            tof_count={'TOF':1})
   ....:     

In [32]: return pt
  File "<ipython-input-32-b5af636976ce>", line 1
    return pt
SyntaxError: 'return' outside function

In [33]: pt.filename = 'JZ.xml'

In [34]: pt.save()

In [35]: import kmos.cli

In [36]: kmos.cli.main('export JZ.xml')
No export path provided. Exporting to JZ_local_smart
## /usr/local/lib/python2.7/dist-packages/kmos

UserWarning                               Traceback (most recent call last)
<ipython-input-36-4cb4228c9e10> in <module>()
----> 1 kmos.cli.main('export JZ.xml')

/usr/local/lib/python2.7/dist-packages/kmos/cli.pyc in main(args)
    307         kmos.io.export_source(project,
    308                               export_dir,
--> 309                               code_generator=options.backend)
    310 
    311         if ((os.name == 'posix'

/usr/local/lib/python2.7/dist-packages/kmos/io.pyc in export_source(project_tree, export_dir, code_generator)
   2017     writer.write_lattice()
   2018     writer.write_proclist(code_generator=code_generator)
-> 2019     writer.write_settings()
   2020     project_tree.validate_model()
   2021     return True

/usr/local/lib/python2.7/dist-packages/kmos/io.pyc in write_settings(self)
   1890             except Exception, e:
   1891                 raise UserWarning('Could not evaluate (%s)\n%s\nProcess: %s'
-> 1892                                   % (process.rate_constant, e, process.name))
   1893         out.write('    }\n\n')
   1894 

UserWarning: Could not evaluate (p_O2gas_bar_A/sqrt(2_pi_m_O2_umass/beta)_exp(beta_(E_bind_O2-mu_O2gas)_eV))

```
Error: Could not import JANAF data
Installing JANAF Thermochemical Tables
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

You can conveniently use gas phase chemical potentials
inserted in rate constant expressions using
JANAF Thermochemical Tables. A couple of molecules
are automatically supported. If you need support
for more gas-phase species, drop me a line.

The tabulated values are not distributed since
the terms of distribution do not permit this.
Fortunately manual installation is easy.
Just create a directory called `janaf_data`
anywhere on your python path. To see the directories on your python
path run ::

    python -c"import sys; print(sys.path)"

    Inside the `janaf_data` directory has to be a file
    named `__init__.py`, so that python recognizes it as a module ::

        touch __init__.py

        Then copy all needed data files from the
        `NIST website <http://kinetics.nist.gov/janaf/>`_
        in the tab-delimited text format
        to the `janaf_data` directory.
```

Process: A_desorption
`

**Comment by mhoffman** [comment]
I would venture to say that the error message is pretty elaborate at explaining why it occurs and how it can be fixed. Have you given it a shot?

**Comment by jiangwangzhang** [comment]
thanks,^ ^.
u mean that I should install the JANAF Thermochemical Tables?

**Comment by jiangwangzhang** [comment]
hi mhoffman.
**I creat a new folder named janaf_data. then in python type as following(but there is no __init__.py):**
`/usr/lib/python2.7$ sudo python -c"import sys; print(sys.path)"
['', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/pymodules/python2.7', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client']
`

**Comment by mhoffman** [comment]
Yeah, you just have to follow the instructions in the error message.

**Comment by jiangwangzhang** [comment]
Hi mhoffman, thanks for your replying.
I try to install the JANAF, and run the AB_model again. but it remind a new  error:Command "AB_model.xml" not understood.
I do not know why. Is there some suggestion for me to run the kmos examples? I ran into too many mistakes when I tried to run these examples. 


`>>> from kmos.types import *
>>> from kmos.io import *
>>> import numpy as np
>>> pt = Project()
>>> pt.meta.author = 'Max J. Hoffmann'
>>> pt.meta.email = 'mjhoffmann@gmail.com'
>>> pt.meta.model_name = 'AB_no_diffusion'
>>> pt.meta.model_dimension = 2
>>> pt.meta.debug = 0
>>> pt.add_species(name='empty')
[SPECIES] Name: empty Color: no color set.

>>> pt.add_species(name='A', representation="Atoms('O')")
[SPECIES] Name: A Color: no color set.

>>> pt.add_species(name='B', representation="Atoms('CO', [[0,0,0],[0,0,1.2]])")
[SPECIES] Name: B Color: no color set.

>>> layer = Layer(name='default')
>>> layer.sites.append(Site(name='a'))
>>> pt.add_layer(layer)
[LAYER] default
[
[[SITE] a            (default_species) [ 0.  0.  0.] ]
]
>>> pt.species_list.default_species = 'empty'
>>> parameters = {}
>>> parameters['p_COgas'] = {'value':1., 'adjustable':True,
...                                          'min':1.e-13, 'max':1.e2,
...                                          'scale':'log'}
>>> parameters['p_O2gas'] = {'value':1., 'adjustable':True,
...                                          'min':1.e-13, 'max':1.e2,
...                                          'scale':'log'}
>>> parameters['T'] = {'value':600}
>>> parameters['A'] = {'value':1.552e-19}
>>> parameters['E_bind_O2'] = {'value':-2.138}
>>> parameters['E_bind_CO'] = {'value':-1.9}
>>> parameters['E_react'] = {'value': 0.9}
>>> for key, value in parameters.iteritems():
...         pt.add_parameter(name=key, **value)
... 
[PARAMETER] Name: A Value: 1.552e-19

[PARAMETER] Name: E_react Value: 0.9

[PARAMETER] Name: p_O2gas Value: 1.0

[PARAMETER] Name: T Value: 600

[PARAMETER] Name: E_bind_CO Value: -1.9

[PARAMETER] Name: E_bind_O2 Value: -2.138

[PARAMETER] Name: p_COgas Value: 1.0

>>> coord = pt.lattice.generate_coord('a.(0,0,0).default')
>>> up = pt.lattice.generate_coord('a.(0,1,0).default')
>>> right = pt.lattice.generate_coord('a.(1,0,0).default')
>>> down = pt.lattice.generate_coord('a.(0,-1,0).default')
>>> left = pt.lattice.generate_coord('a.(-1,0,0).default')
>>> pt.add_process(name='A_adsorption',\
  File "<stdin>", line 7
    rate_constant='p\
                   ^
SyntaxError: invalid syntax
>>> pt.add_process(name='A_adsorption',\
...                rate_constant='p_O2gas*bar*A/sqrt(2*pi*m_O2*umass/beta)',\
...                condition_list=[Condition(coord=coord, species='empty')],\
...                action_list=[Action(coord=coord, species='A')],)
[PROCESS] Name:A_adsorption
     Rate: p_O2gas*bar*A/sqrt(2*pi*m_O2*umass/beta)
Conditions: [[COND_ACT] Species: empty Coord:[COORD] a.(0, 0, 0).default
]
Actions: [[COND_ACT] Species: A Coord:[COORD] a.(0, 0, 0).default
]
>>> pt.add_process(name='A_desorption',\
...                rate_constant='p_O2gas*bar*A/sqrt(2*pi*m_O2*umass/beta)\
... *exp(beta*(E_bind_O2-mu_O2gas)*eV)',\
...                condition_list=[Condition(coord=coord, species='A')],\
...                action_list=[Action(coord=coord, species='empty')],)
  File "<stdin>", line 3
SyntaxError: keyword argument repeated
>>> 
KeyboardInterrupt
>>> pt.add_process(name='A_desorption',\
...                rate_constant='p_O2gas*bar*A/sqrt(2*pi*m_O2*umass/beta)\
...                *exp(beta*(E_bind_O2-mu_O2gas)*eV)',\
...                condition_list=[Condition(coord=coord, species='A')],\
...                action_list=[Action(coord=coord, species='empty')],)
[PROCESS] Name:A_desorption
     Rate: p_O2gas*bar*A/sqrt(2*pi*m_O2*umass/beta)               *exp(beta*(E_bind_O2-mu_O2gas)*eV)
Conditions: [[COND_ACT] Species: A Coord:[COORD] a.(0, 0, 0).default
]
Actions: [[COND_ACT] Species: empty Coord:[COORD] a.(0, 0, 0).default
]
>>> pt.add_process(name='B_adsorption',
...                rate_constant='p_COgas*bar*A/sqrt(2*pi*m_CO*umass/beta)',
...                condition_list=[Condition(coord=coord, species='empty')],
...                action_list=[Action(coord=coord, species='B')],)
[PROCESS] Name:B_adsorption
     Rate: p_COgas*bar*A/sqrt(2*pi*m_CO*umass/beta)
Conditions: [[COND_ACT] Species: empty Coord:[COORD] a.(0, 0, 0).default
]
Actions: [[COND_ACT] Species: B Coord:[COORD] a.(0, 0, 0).default
]
>>> pt.add_process(name='B_desorption',
...                rate_constant='p_COgas*bar*A/sqrt(2*pi*m_CO*umass/beta)\
...                *exp(beta*(E_bind_CO-mu_COgas)*eV)',
...                condition_list=[Condition(coord=coord, species='B')],
...                action_list=[Condition(coord=coord, species='empty')],)
[PROCESS] Name:B_desorption
     Rate: p_COgas*bar*A/sqrt(2*pi*m_CO*umass/beta)               *exp(beta*(E_bind_CO-mu_COgas)*eV)
Conditions: [[COND_ACT] Species: B Coord:[COORD] a.(0, 0, 0).default
]
Actions: [[COND_ACT] Species: empty Coord:[COORD] a.(0, 0, 0).default
]
>>> for neighbor, name in [(right, 'right'),
...                            (left, 'left'),
...                            (up, 'up'),
...                            (down, 'down')]:
...     pt.add_process(name='AB_react_%s' % name,
...                    rate_constant='1/(beta*h)*exp(-beta*E_react*eV)',
...                    condition_list=[Condition(coord=coord, species='A'),
...                                    Condition(coord=neighbor, species='B')],
...                    action_list=[Action(coord=coord, species='empty'),
...                                Action(coord=neighbor, species='empty')],
...                    tof_count={'TOF':1})
... 
[PROCESS] Name:AB_react_right
     Rate: 1/(beta*h)*exp(-beta*E_react*eV)
Conditions: [[COND_ACT] Species: A Coord:[COORD] a.(0, 0, 0).default
, [COND_ACT] Species: B Coord:[COORD] a.(1, 0, 0).default
]
Actions: [[COND_ACT] Species: empty Coord:[COORD] a.(0, 0, 0).default
, [COND_ACT] Species: empty Coord:[COORD] a.(1, 0, 0).default
]
[PROCESS] Name:AB_react_left
     Rate: 1/(beta*h)*exp(-beta*E_react*eV)
Conditions: [[COND_ACT] Species: A Coord:[COORD] a.(0, 0, 0).default
, [COND_ACT] Species: B Coord:[COORD] a.(-1, 0, 0).default
]
Actions: [[COND_ACT] Species: empty Coord:[COORD] a.(0, 0, 0).default
, [COND_ACT] Species: empty Coord:[COORD] a.(-1, 0, 0).default
]
[PROCESS] Name:AB_react_up
     Rate: 1/(beta*h)*exp(-beta*E_react*eV)
Conditions: [[COND_ACT] Species: A Coord:[COORD] a.(0, 0, 0).default
, [COND_ACT] Species: B Coord:[COORD] a.(0, 1, 0).default
]
Actions: [[COND_ACT] Species: empty Coord:[COORD] a.(0, 0, 0).default
, [COND_ACT] Species: empty Coord:[COORD] a.(0, 1, 0).default
]
[PROCESS] Name:AB_react_down
     Rate: 1/(beta*h)*exp(-beta*E_react*eV)
Conditions: [[COND_ACT] Species: A Coord:[COORD] a.(0, 0, 0).default
, [COND_ACT] Species: B Coord:[COORD] a.(0, -1, 0).default
]
Actions: [[COND_ACT] Species: empty Coord:[COORD] a.(0, 0, 0).default
, [COND_ACT] Species: empty Coord:[COORD] a.(0, -1, 0).default
]
>>> pt.filename = 'AB_model.xml'
>>> pt.save()
>>> import kmos.cli
>>> kmos.cli.main('AB_model.xml')
Usage:  [help] (all|benchmark|build|edit|export|help|import|rebuild|run|settings-export|shell|version|view|xml) [options]

: error: Command "AB_model.xml" not understood.
`

**Comment by FuzhuLiu** [comment]
Hi, @jiangwangzhang , I have installed janaf_data, but still can't import JANAF data.
Can you tell me how to correctly use the tables.
