### ISSUE TITLE
Segmentation fault on import of pygoocanvas module

### ISSUE THREAD

**Issue by DarthJJBinks** [mhoffman/kmos#49]
Hello Max,

I have installed the pygoocanvas module using the command, `sudo port install py27-goocanvas` on my Mac system running on OS X 10.11.5.  The installation was successful, however importing the module using the command `import goocanvas` immediately results in a seg fault error `Segmentation fault 11`. I believe the module is necessary to use the editor window, as I am getting the same error with `kmos edit <model-file>.(xml/ini)`. How do I come around this error?

Thanks,
Viswanath.

**Comment by mhoffman** [comment]
Hi​ Viswanath

I haven't yet had time to upgrade/play with 10.11.5. Yes, `kmos edit ` uses
`goocanvas` but I don't have a workaround for this.

Best,
Max.

**Comment by DarthJJBinks** [comment]
Thanks for the reply Max. I remember from your previous comment that you use 10.11.4. Does `import goocanvas` work fine with 10.11.4?

**Comment by mhoffman** [comment]
Yes it does.
